version: "3.3"

services:
  db:
   build: 
     context: .
     dockerfile: Dockerfiles/DockerfileMySQL
   restart: always
   #Este comando permite iniciar sesión desde phpMyAdmin en MySQL.
   command: --default-authentication-plugin=mysql_native_password 

  payara:
   build: 
     context: .
     dockerfile: Dockerfiles/DockerfilePayara
   restart: always
   depends_on:
     - db
   ports:
     - "8080:8080"
     - "8181:8181"
     - "4848:4848"
   volumes:
     - ./Aplicaciones:/opt/payara/deployments

  php:
   image: phpmyadmin/phpmyadmin:4.8.5
   ports:
     - "8000:80"
   depends_on:
     - db